### ISSUE TITLE
Possible speed improvement in inla.spde.make.A

### ISSUE THREAD

**Issue by arthfen** [finnlindgren/fmesher#14] opened 2024-03-29 09:01 UTC
Hello,

I have been dealing with a problem where inla.spde.make.A has to be called many times for a relatively large number of points.
When investigating function behavior, I noticed that splitting my points into smaller subsets could lead to a performance increase.

I tested in two machines and had a similar behavior, but I was wondering if that could be reproduced and eventually become a trigger inside the corresponding fmesher function.

I attach a reproducible example for a large number of points ("mat_large.rds") and a small number of points ("mat_small.rds'). In the later, I don't get any performance changes.

But in the former, with the original inla.spde.make.A, I get:
- Machine 1
>  user  system elapsed
>  8.304   0.184   8.508
- Machine 2 
>  user  system elapsed 
>  3.975   3.587   7.562 

And with the modified inla.spde.make.A_f:
- Machine 1
>   user  system elapsed
>  2.174   0.057   2.235 
- Machine 2
>   user  system elapsed 
>  1.325   0.000   1.325 

My INLA versions are:
- Machine 1
> INLA_24.03.24 built 2024-03-24 18:07:06 UTC.
- Machine 2
> INLA_24.02.09 built 2024-02-09 03:35:28 UTC.

My R version is:
> platform       x86_64-pc-linux-gnu
> arch           x86_64
> os             linux-gnu
> system         x86_64, linux-gnu
> status
> major          4
> minor          2.3 
> year           2023
> month          03
> day            15 
> svn rev        83980
> language       R
> version.string R version 4.2.3 (2023-03-15)
> nickname       Shortstop Beagle

[alternative_f.zip](https://github.com/inlabru-org/fmesher/files/14801904/alternative_f.zip)

**Comment by finnlindgren** [comment] 2024-04-03 15:46
Thanks for the testing code! I've confirmed empirically that computational block batching does speed things up, and that batches should be kept at or below ca 200,000 for optimal performance, as shown in the graph below. It's not clear _why_ this happens, but I suspect it's related to memory allocation issues. I'll implement a version of your batch method to get around it.

[comparison_plot.pdf](https://github.com/inlabru-org/fmesher/files/14854905/comparison_plot.pdf)

```r
library(INLA)
library(fmesher)

location <- "/home/flindgre/git/inlabru-issues/fmesher-speed"
sm_var = readRDS(file.path(location, 'mesh.rds'))
tmp = readRDS(file.path(location, 'mat_large.rds'))

# alternative function splitting the large matrix into smaller ones
inla.spde.make.A_f <- function(obj, loc, k){
	n <- nrow(loc)
	n = unique(round(seq(0, n, length.out = k+1), 0))
	l = lapply(seq_len(length(n) - 1), function(j){
	  v <- inla.spde.make.A(obj, loc[(n[j] + 1):n[j+1],,drop=FALSE])
	  v
	})
	l = do.call(rbind, l)
	l
}

loc <- cbind(tmp$x1, tmp$x2, 0)
loc <- rbind(loc, loc, loc, loc, loc)

K_max <- 10
p0 = inla.spde.make.A(sm_var, loc)
p1 = inla.spde.make.A_f(sm_var, loc, k = K_max)
all.equal(p0, p1)
identical(p0, p1)



t0 <- NULL
t1 <- NULL
for (the_size in c(10, 20, 50,
                   100, 200, 500,
                   1000, 2000, 5000,
                   10000, 20000, 50000,
                   100000, 200000, 500000,
                   1000000, 2000000, 5000000)) {
  t0 <- rbind(t0, c(system.time({
    p0 = inla.spde.make.A(sm_var, loc[1:the_size,,drop=FALSE])
  }), k = 1, size = the_size))
  for (k in 2^(0:10)) {
    t1 <- rbind(t1, c(system.time({
      p1 = inla.spde.make.A_f(sm_var, loc[1:the_size,,drop=FALSE], k = k)
    }), k = k, size = the_size))
  }
  print(rbind(
    t0[t0[,"size"] == the_size,],
    t1[t1[,"size"] == the_size,]))
}

t0 <- as.data.frame(t0)
t1 <- as.data.frame(t1)
t0$block_size <- ceiling(t0$size / t0$k)
t1$block_size <- ceiling(t1$size / t1$k)

library(ggplot2)
p_total_total <-
  ggplot() +
  geom_point(aes(size, user.self), data = t0) +
  geom_line(aes(size, user.self,
                col = as.factor(k)), data = t1) +
  xlab("Total data size") +
  ylab("Total computing time") +
  scale_x_log10() +
  scale_y_log10() +
  geom_vline(xintercept = 2e5, col = "red") +
  ggtitle("Total time")

p_total_rate <-
  ggplot() +
  geom_point(aes(size, user.self/size), data = t0) +
  geom_line(aes(size, user.self/size,
                col = as.factor(k)), data = t1) +
  xlab("Total data size") +
  ylab("Computing time per location") +
  scale_x_log10() +
  scale_y_log10() +
  geom_vline(xintercept = 2e5, col = "red") +
  ggtitle("Time per location")

p_block_total <-
  ggplot() +
  geom_point(aes(block_size, user.self), data = t0) +
  geom_line(aes(block_size, user.self,
                col = as.factor(size)), data = t1) +
  xlab("Computational block size") +
  ylab("Total computing time") +
  scale_x_log10() +
  scale_y_log10() +
  geom_vline(xintercept = 2e5, col = "red") +
  ggtitle("Total time, by block size")

p_block_rate <-
  ggplot() +
  geom_point(aes(block_size, user.self/size), data = t0) +
  geom_line(aes(block_size, user.self/size,
                col = as.factor(size)), data = t1) +
  xlab("Computational block size") +
  ylab("Computing time per location") +
  scale_x_log10() +
  scale_y_log10() +
  geom_vline(xintercept = 2e5, col = "red") +
  ggtitle("Time per location, by block size")

library(patchwork)
(
  (p_total_total | p_total_rate) /
    (p_block_total | p_block_rate)
) +
  plot_layout(guides = "collect")
```

**Comment by arthfen** [comment] 2024-04-03 16:48
Very nice, thank you for the response! I also believe this relates to memory allocation, since it seems to be by far the most time consuming step of the original function on the large test set (according to profvis)...

**Comment by finnlindgren** [comment] 2024-04-03 17:17
Updated plot for version `0.1.5.9002`, that uses batched computation for data sizes of `2e5` and above. I'll add this as an adjustable option, but it seems to be consistent.
[comparison_plot_batch_implementation.pdf](https://github.com/inlabru-org/fmesher/files/14856005/comparison_plot_batch_implementation.pdf)

**Comment by finnlindgren** [comment] 2024-06-14 16:55
Version 0.1.6 with this feature has now been submitted to CRAN. The cutoff is still hardwired to `2e5`.

**Comment by finnlindgren** [comment] 2024-11-05 16:42
As the control argument `max_batch_size` has now been added, marking this as solved-in-devel until the next CRAN release, which will be very soon, as `0.2.0`.

**Closed as completed** 2024-11-14 17:04 UTC
Labels: enhancement, solved-in-devel
